version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Australia/Sydney"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Australia/Sydney"
