name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: strongishllama/github-actions/.github/workflows/typescript-lint.yml@main
